version: "3.9"

services:
  datamigration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datamigration-dev
    ports:
      - "5050:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      ConnectionStrings__PostgreSql: >
        Host=host.docker.internal;
        Port=5432;
        Database=navikaran;
        Username=admin;
        Password=admin123
    volumes:
      - .:/app
      - ./logs:/app/logs
      - dataprotection-keys:/app/keys
    networks:
      - migration-network

networks:
  migration-network:
    driver: bridge

volumes:
  dataprotection-keys:
